# swagger : http://localhost:8080/swagger-ui/index.html

###
# 게시판 목록 조회
GET http://localhost:8080/boards

###
# 게시글 상세 조회
GET http://localhost:8080/boards/11

###
# 게시글 등록
POST http://localhost:8080/boards
Content-Type: application/json

{
  "title": "안녕하세요",
  "content": "만나서 반가워요",
  "writerId": 2
}

###
# 게시글 수정
PUT http://localhost:8080/boards/11
Content-Type: application/json

{
  "title": "안녕하세요 수정합니다",
  "content": "만나서 반가워요",
  "editorId": 3
}

###
# 게시글 삭제
DELETE http://localhost:8080/boards/9